#!/bin/bash

alias grep="grep --color=auto -Hn"

# ls 
alias ls='ls --hide "*~" --hide "#*#" --color=auto'
alias ll='ls -alF'
alias la='ls -A'
#alias nls='ls -I "*.$1"'
function nls()
{
  arg="ls --hide \"*~\" --hide \"#*#\" --color=auto"
  space=" "
  for i in $@
    do
        arg=$arg$space"-I\"*$i\""
    done
  eval $arg
}


function lsf()
{
  DIR="."
  if [ -n $1 ];then
     DIR=$1
  fi
  find $DIR -maxdepth 1 -type f -not  -name ".*" | xargs ls --color=auto -l
}

function lsd()
{
  DIR="."
  if [ -n $1 ];then
     DIR=$1
  fi
  find $DIR -maxdepth 1 -type d -not  -name ".*" | xargs ls --color=auto -ld
}



# cd
alias ..='cd ..'
up() { [ $(( $1 + 0 )) -gt 0 ] && cd $(eval "printf '../'%.0s {1..$1}"); }
ck() {(cd $1 && ls)}



# find
function findf()
{
  find . -type f | xargs -I {} grep --color=auto -Hn "$1" {}
}

function findc()
{
  find . -type f -name "*.c" -o -name "*.cpp" | xargs -I {} grep --color=auto -Hn "$1" {}
}

function findh()
{
  find . -type f -name "*.h" -o -name "*.hpp" | xargs -I {} grep --color=auto -Hn "$1" {}
}

function findj()
{
  find . -type f -name "*.java" | xargs -I {} grep --color=auto -Hn "$1" {}
}




# reboot/shutdown
alias reboot='sudo reboot'
alias shutdown='sudo shutdown -P now'

alias 'ps?'='ps ax | grep '

alias mnt='mount | column -t'
alias emacs='LC_CTYPE=zh_CN.utf8 emacs -nw'
alias emacsw='LC_CTYPE=zh_CN.utf8 emacs'
